[package]
description = "An experimental Tauri Plugin for Sentry"
edition = "2021"
license = "MIT OR Apache-2.0"
name = "sentry-tauri"
readme = "README.md"
repository = "https://github.com/timfish/sentry-tauri"
version = "0.3.0"

[dependencies]
base64 = "0.22"
sentry = { version = "0.34.0", features = ["metrics"] }
sentry-rust-minidump = "0.7"
serde = "1"
tauri = "1"
thiserror = "1"
